#!/usr/bin/env python3
"""build_exe.py -- bundle keel into ONE file, and prepare the real executable.

    python3 keel/build_exe.py

Produces, in keel/dist/:

    keel.cjs          one self-contained CommonJS file. No imports, no
                      node_modules, no network. `node keel.cjs check "..."`
                      works on Windows, macOS and Linux as-is.
    sea-config.json   Node's single-executable configuration
    keel.blob         the prepared payload (built here, offline)
    keel.cmd          Windows launcher
    keel              macOS/Linux launcher

THE ACTUAL BINARY
    python3 keel/build_exe.py --binary

injects keel.blob into a copy of the node binary with `postject` and produces a
single file that runs with NO node installed and an empty environment. That was
done here and verified: a 124 MB Linux binary answering `env -i ./keel check`.
The same two commands on Windows produce keel.exe.

Two things are still not done for you and cannot be: the injection needs one npm
package (postject), and shipping a .exe to other people needs a code-signing
certificate -- without one Windows SmartScreen warns every person who downloads
it. The binary is also ~124 MB, because it contains a whole copy of node, so it
is deliberately NOT committed to this repository. What this script will never do
is produce a file called keel.exe that is really a shell script, because that is
exactly the kind of thing this project exists to catch.
"""
import json
import os
import re
import shutil
import subprocess
import sys

# Node bakes this sentinel into every binary that can carry a payload.
FUSE = "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2"

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DIST = os.path.join(HERE, "dist")


def read(p):
    return open(p, encoding="utf-8").read()


def strip_esm(src):
    """Turn one of our ESM modules into a plain script body.

    Only the forms this project actually uses are handled, and anything else
    raises rather than being silently mangled -- a bundler that quietly drops a
    line is exactly the failure mode the parity tests elsewhere exist to catch.
    """
    src = re.sub(r"^import\s+[^;]+?;\s*$", "", src, flags=re.M)
    src = re.sub(r"^export\s+(const|function|class|let|var)\s", r"\1 ", src, flags=re.M)
    src = re.sub(r"^export\s*\{[^}]*\};?\s*$", "", src, flags=re.M)
    leftover = [ln for ln in src.splitlines()
                if re.match(r"^\s*(import|export)\s", ln)]
    if leftover:
        raise SystemExit("build_exe.py cannot handle these lines:\n  " + "\n  ".join(leftover))
    return src


def main():
    os.makedirs(DIST, exist_ok=True)

    engine = read(os.path.join(ROOT, "cairn/ei_engine.js"))
    kernel = strip_esm(read(os.path.join(HERE, "kernel.mjs")))
    cli = strip_esm(read(os.path.join(HERE, "cli.mjs")))
    policy = json.loads(read(os.path.join(HERE, "policy.example.json")))

    # The only edits the bundle needs: drop the two module-level path lookups
    # (there is no file layout inside a single file) and the argv bootstrap,
    # which the bundle does itself at the end. The policy needs no surgery --
    # cli.mjs resolves it through loadPolicy(), which finds BAKED_POLICY.
    cli = cli.replace('const here = dirname(fileURLToPath(import.meta.url));', "")
    cli = re.sub(r"if \(process\.argv\[1\].*?\n\}\n", "", cli, flags=re.S)
    kernel = kernel.replace('const here = dirname(fileURLToPath(import.meta.url));', "")
    kernel = kernel.replace('const ROOT = dirname(here);', "")
    kernel = kernel.replace('const require = createRequire(import.meta.url);', "")
    kernel = kernel.replace('const EI = require(join(ROOT, "cairn/ei_engine.js"));', "")

    bundle = f"""#!/usr/bin/env node
/* keel -- one file, no dependencies, no network.
 * BUILT by keel/build_exe.py from cairn/ei_engine.js, keel/kernel.mjs and
 * keel/cli.mjs. Do not edit this file; edit those and rebuild. Parity with the
 * sources is asserted by keel/test_exe.py.
 */
"use strict";
const {{ createHash }} = require("node:crypto");
const {{ readFileSync }} = require("node:fs");

const BAKED_POLICY = {json.dumps(policy, separators=(",", ":"))};

/* ---------------------------------------------- cairn/ei_engine.js ------ */
const EI = (function () {{
  const module = {{ exports: {{}} }};
{engine}
  return module.exports;
}})();

/* ---------------------------------------------- keel/kernel.mjs --------- */
{kernel}

/* ---------------------------------------------- keel/cli.mjs ------------ */
{cli}

process.exitCode = run(process.argv.slice(2));
"""
    out = os.path.join(DIST, "keel.cjs")
    open(out, "w", encoding="utf-8").write(bundle)
    os.chmod(out, 0o755)

    sea = {"main": "keel.cjs", "output": "keel.blob", "disableExperimentalSEAWarning": True}
    open(os.path.join(DIST, "sea-config.json"), "w", encoding="utf-8").write(
        json.dumps(sea, indent=2) + "\n")

    open(os.path.join(DIST, "keel.cmd"), "w", encoding="utf-8", newline="\r\n").write(
        "@echo off\r\nnode \"%~dp0keel.cjs\" %*\r\n")
    launcher = os.path.join(DIST, "keel")
    open(launcher, "w", encoding="utf-8").write(
        '#!/bin/sh\nexec node "$(dirname "$0")/keel.cjs" "$@"\n')
    os.chmod(launcher, 0o755)

    # prepare the payload -- this part is offline and runs here
    blob_ok, blob_note = False, ""
    try:
        r = subprocess.run(["node", "--experimental-sea-config", "sea-config.json"],
                           cwd=DIST, capture_output=True, text=True, timeout=180)
        blob_ok = r.returncode == 0 and os.path.exists(os.path.join(DIST, "keel.blob"))
        blob_note = (r.stderr or r.stdout).strip().splitlines()[-1:] and \
            (r.stderr or r.stdout).strip().splitlines()[-1] or ""
    except Exception as e:                                    # noqa: BLE001
        blob_note = str(e)

    if blob_ok and "--binary" in sys.argv:
        machine = os.uname().machine if hasattr(os, "uname") else "x64"
        target = "keel.exe" if sys.platform.startswith("win") else f"keel-{sys.platform}-{machine}"
        node_bin = subprocess.run(["node", "-e", "process.stdout.write(process.execPath)"],
                                  capture_output=True, text=True).stdout
        shutil.copyfile(node_bin, os.path.join(DIST, target))
        os.chmod(os.path.join(DIST, target), 0o755)
        r = subprocess.run(["npx", "--yes", "postject", target, "NODE_SEA_BLOB", "keel.blob",
                            "--sentinel-fuse", FUSE], cwd=DIST, capture_output=True,
                           text=True, timeout=900)
        if r.returncode == 0:
            mb = os.path.getsize(os.path.join(DIST, target)) / 1e6
            print(f"wrote dist/{target}  ({mb:.0f} MB) — runs with no node installed")
        else:
            print("the injection step failed:", (r.stderr or r.stdout).strip()[-300:])

    # A bundler is only as good as its check. Parsing is not enough -- the bug
    # that got through last time was a dangling reference, which parses fine --
    # so every command is actually RUN before the file is called built.
    smoke = [["version"], ["help"], ["key"], ["check", "a 2024 audit of 30 clinics in the UK"]]
    for cmd in smoke:
        r = subprocess.run(["node", out, *cmd], capture_output=True, text=True, timeout=120)
        if r.returncode != 0:
            raise SystemExit("the bundle does not run `keel " + " ".join(cmd) + "`:\n" +
                             (r.stderr or r.stdout).strip()[-600:])
    probe = os.path.join(DIST, ".smoke-actions.json")
    open(probe, "w", encoding="utf-8").write('[{"verb":"read","target":"projects/a.md"}]')
    r = subprocess.run(["node", out, "run", probe], capture_output=True, text=True, timeout=120)
    os.remove(probe)
    if r.returncode != 0:
        raise SystemExit("the bundle does not run `keel run`:\n" +
                         (r.stderr or r.stdout).strip()[-600:])

    size = os.path.getsize(out) / 1024
    print(f"wrote dist/keel.cjs        ({size:.1f} KB) — runs anywhere node runs")
    print("wrote dist/keel.cmd        — Windows")
    print("wrote dist/keel            — macOS / Linux")
    print("wrote dist/sea-config.json")
    if blob_ok:
        b = os.path.getsize(os.path.join(DIST, "keel.blob")) / 1024
        print(f"wrote dist/keel.blob       ({b:.1f} KB) — payload for a real binary")
        print()
        print("  To finish a real keel.exe on Windows (needs one npm install):")
        print("    node -e \"require('fs').copyFileSync(process.execPath,'keel.exe')\"")
        print("    npx postject keel.exe NODE_SEA_BLOB keel.blob \\")
        print(f"      --sentinel-fuse {FUSE}")
        print("  Or, right here:   python3 keel/build_exe.py --binary")
        print("  Then sign it, or Windows will warn everyone who downloads it.")
    else:
        print(f"note: the payload step did not run here ({blob_note or 'no detail'}).")
        print("      dist/keel.cjs still works everywhere: node keel.cjs check \"...\"")
    if shutil.which("node") is None:
        print("note: node was not found on PATH")
    return 0


if __name__ == "__main__":
    sys.exit(main())
