#!/usr/bin/env python3
"""build_bundle.py -- assemble novora-suite/engine.bundle.js for the browser.

    python3 novora-suite/build_bundle.py

The nine Novora screens run on `engine/fastmode.mjs`, which imports two helpers
from elsewhere in the stack. A browser opening a file:// page cannot follow ES
module imports, so this script inlines exactly those helpers and emits one IIFE.

This is a hand-rolled bundler, which is a liability: a silent extraction error
would give the browser a DIFFERENT engine from the one the test suite exercises.
That is why novora-suite/test_bundle_parity.mjs runs the real module and the
bundle over the same inputs across all nine products and fails on any
divergence. The bundle is not trusted; it is checked.

Extraction is anchored on explicit markers rather than line numbers, and every
anchor is asserted, so a source edit that moves these functions fails the build
loudly instead of producing a subtly wrong bundle.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def read(rel):
    return open(os.path.join(ROOT, rel), encoding="utf-8").read()


def slice_between(src, start_marker, end_marker, what):
    i = src.find(start_marker)
    assert i != -1, f"anchor not found while extracting {what}: {start_marker!r}"
    j = src.find(end_marker, i + len(start_marker))
    assert j != -1, f"end anchor not found while extracting {what}: {end_marker!r}"
    return src[i:j].rstrip() + "\n"


govern = read("api/govern.js")
pages = read("pages/pages.mjs")
fast = read("novora-suite/engine/fastmode.mjs")

# --- from api/govern.js: the pattern table, its counter, and the fast extractor
g_patterns = slice_between(govern, "const P = {", "const count = (pats, t)", "P table")
g_count = "const count = (pats, t) => pats.reduce((n, p) => n + (p.test(t) ? 1 : 0), 0);\n"
assert g_count.strip() in govern, "the count() helper changed shape in api/govern.js"
g_extract = slice_between(govern, "function extractEvidenceFast(text)",
                          "// CORROBORATION GATE", "extractEvidenceFast")

# --- from pages/pages.mjs: fast-mode grounding
p_ground = slice_between(pages, "const STOP = new Set(", "const metaOf =", "groundFast")
p_ground = p_ground.replace("export function groundFast", "function groundFast")

# --- from engine/fastmode.mjs: everything except its imports/exports
f_body = re.sub(r"^import .*?;\s*$", "", fast, flags=re.M)
f_body = f_body.replace("export const PRODUCT_IDS", "const PRODUCT_IDS")
f_body = f_body.replace("export function screen", "function screen")
assert "export " not in f_body, "an unhandled export survived in the fastmode body"
assert "import " not in f_body, "an unhandled import survived in the fastmode body"
# fastmode declares its own clip/hex8/band/count; ours would collide.
f_body = f_body.replace("const count = (text, re) => (text.match(re) || []).length;",
                        "const countRe = (text, re) => (text.match(re) || []).length;")
f_body = re.sub(r"\bcount\(text, /", "countRe(text, /", f_body)
f_body = re.sub(r"\bcount\((\w+), /", r"countRe(\1, /", f_body)

OUT = f"""/* engine.bundle.js — GENERATED by novora-suite/build_bundle.py. Do not edit.
 *
 * The nine Novora screens, inlined for the browser. Parity with the real ES
 * module is asserted by novora-suite/test_bundle_parity.mjs over all nine
 * products; if this file drifts from engine/fastmode.mjs, that test fails.
 *
 * Honest scope, carried over verbatim from the engine: fast mode is a SCREEN,
 * not a semantic judge. It agrees with deep mode on the clear cases and returns
 * a calibrated score plus the product's verdict enum. Genuine
 * paraphrase-vs-substance on the ambiguous middle is not something this can do,
 * and a confident-looking number here is not a judgement about a person.
 */
(function (root) {{
"use strict";

// ---- inlined from api/govern.js -------------------------------------------
{g_patterns}
{g_count}
{g_extract}
// ---- inlined from pages/pages.mjs -----------------------------------------
{p_ground}
// ---- novora-suite/engine/fastmode.mjs -------------------------------------
{f_body}

root.NOVORA = {{ screen: screen, PRODUCT_IDS: PRODUCT_IDS }};
}})(typeof globalThis !== "undefined" ? globalThis : this);
"""

path = os.path.join(HERE, "engine.bundle.js")
open(path, "w", encoding="utf-8").write(OUT)
print("wrote engine.bundle.js  (%.1f KB) — run test_bundle_parity.mjs to verify it"
      % (len(OUT) / 1024))
