"""
gt_regimes.py — GT v18.1 Two-Regime Constitutive Structure
==========================================================
QG-COS / Governance Thermodynamics · Layer 1–2 module · July 2026

WHAT THIS MODULE IS
-------------------
The canonical formalization of the discovery produced by the 2026 multi-domain
campaign's *negative and inconclusive* results (US-Legislative CAP, Swiss BGer
118k-case corpus):

    E = U·D is not the constitutive relation of governance.
    It is the constitutive relation of ONE CHANNEL ROLE — transmission.
    Governance systems contain at least one other role — correction — whose
    realized output is generated by CONSUMING upstream infidelity, not by
    transmitting fidelity. Its observable-output law is therefore inverted
    in D_in, and any transmission-law instrument pointed at it necessarily
    reads k ≈ 0 with a negative tilt. That reading is a DIAGNOSTIC of
    regime misclassification, not a falsification of GT.

CONSEQUENCE FOR THE OS: laws are regime-local. Regime identification
(Gate 0) precedes law application. See Governance OS Architecture v3 §9.5.

EPISTEMIC STATUS (Layer discipline — do not blur)
-------------------------------------------------
  R_T law  E = U·D ................ SUPPORTED (linear; yeast, GitHub, finance).
  R_C law  E_c = U·κ(1−D_in)·q .... HYPOTHESIS. Post-hoc: generated by the
           same BGer data whose five-level ordering it explains. It ships
           with locked, directional predictions (P1–P4 below) and may not
           be described as validated until they run out-of-sample.
  Quadratic E = U·D² .............. RETIRED as descriptive law (no domain
           supports it). Retained ONLY as the prescriptive Lyapunov floor
           inside the IHCEI kernel — an architect-imposed gate, not physics.
  SELECTION channels .............. NO validated D-law. The CAP legislative
           null (hollow-encoding ⊬ passage; majority-party dominated) says
           throughput there is governed by power covariates; and the corpus
           had no live decode hop, so D was uninstantiable (dead channel).

Provenance: BGer k̂ = −0.12 [−0.13, −0.11] under E=U·D^k (transmission
instrument); five-level citation ordering writeoff≈inadmissible(≈1) <
rejected(3) < granted(4) ≤ partly(5); granted/partly = 1.24× rejected,
length-adjusted, p≈0. Legislative: D_dec ≡ 0 (placeholder tracking fields),
so D_gap collapsed to D_enc — category error, not evidence.
"""

from __future__ import annotations
import json
import hashlib
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Optional, Sequence


# ─────────────────────────────────────────────────────────────────────────────
# 1. Regimes and law registry
# ─────────────────────────────────────────────────────────────────────────────

class Regime(str, Enum):
    TRANSMISSION = "TRANSMISSION"   # engine: produces output under load through fidelity
    CORRECTION   = "CORRECTION"     # entropy pump: repairs upstream infidelity
    SELECTION    = "SELECTION"      # chooses among competing items under power
    UNKNOWN      = "UNKNOWN"


class LawStatus(str, Enum):
    SUPPORTED           = "SUPPORTED"             # multi-domain, pre-registered support
    HYPOTHESIS          = "HYPOTHESIS"            # post-hoc; predictions locked, untested
    RETIRED_DESCRIPTIVE = "RETIRED_DESCRIPTIVE"   # kept only as prescriptive constraint
    NOT_APPLICABLE      = "NOT_APPLICABLE"        # no validated D-law for this regime


LAWS = {
    Regime.TRANSMISSION: {
        "form": "E = U * D",
        "status": LawStatus.SUPPORTED,
        "evidence": ["yeast interactome (linear)", "GitHub cohort (linear)",
                     "financial panel N≈4,500 (linear decisively)"],
        "reading": "Output scales with load × two-hop fidelity. The engine law.",
    },
    Regime.CORRECTION: {
        "form": "E_c = U * kappa * (1 - D_in) * q",
        "status": LawStatus.HYPOTHESIS,
        "evidence": ["BGer 118k signature: five-level ordering + 1.24× reversal premium "
                     "+ k̂≈0 under transmission instrument (post-hoc; explains, "
                     "not yet predicts)"],
        "reading": "Visible output ∝ infidelity captured (1−D_in) × the corrector's own "
                   "decode quality q × detection sensitivity κ. The pump law. "
                   "Procedural non-engagement (no repair attempted) → E_c ≈ 0.",
    },
    Regime.SELECTION: {
        "form": None,
        "status": LawStatus.NOT_APPLICABLE,
        "evidence": ["CAP legislative null: encoding-hollowness ⊬ passage; "
                     "majority-party status dominated"],
        "reading": "Throughput governed by power covariates; no validated coupling to D. "
                   "Do not fit E=U·D^k here and report the exponent as physics.",
    },
}

QUADRATIC_NOTE = ("E = U·D² is RETIRED as a descriptive law (supported in no domain). "
                  "It survives only as the IHCEI kernel's prescriptive Lyapunov floor — "
                  "an engineering choice the architect imposes on their own system, "
                  "which owes efficacy evidence (the D-floor shadow pilot) before it "
                  "may be asked of anyone else.")


# ─────────────────────────────────────────────────────────────────────────────
# 2. The empirical ledger (machine-readable; update only via pre-registered runs)
# ─────────────────────────────────────────────────────────────────────────────

EMPIRICAL_LEDGER = [
    {"domain": "biological (yeast interactome)",  "regime": "TRANSMISSION",
     "verdict": "linear supported", "note": "two-hop telemetry"},
    {"domain": "software (GitHub cohort)",        "regime": "TRANSMISSION",
     "verdict": "linear supported", "note": "two-hop telemetry; τ_v p=0.0146"},
    {"domain": "financial (firm panel)",          "regime": "TRANSMISSION",
     "verdict": "linear decisively > quadratic", "note": "quadratic retired"},
    {"domain": "legislative (CAP public laws)",   "regime": "SELECTION",
     "verdict": "INCONCLUSIVE — dead channel",
     "note": "D_dec ≡ 0 placeholder; D_gap = D_enc identically; category error"},
    {"domain": "judicial (BGer 118k)",            "regime": "CORRECTION (discovered)",
     "verdict": "transmission law inapplicable; R_C signature observed",
     "note": "k̂=−0.12 [−0.13,−0.11]; ordering writeoff≈inadm < rejected < granted≤partly; "
             "reversal premium 1.24× length-adjusted → generated H_C (HYPOTHESIS)"},
]


# ─────────────────────────────────────────────────────────────────────────────
# 3. Gate 0 — regime classification (precedes ALL law application)
# ─────────────────────────────────────────────────────────────────────────────

_RUBRIC = {
    Regime.TRANSMISSION: (
        "produce", "build", "ship", "deliver", "transmit", "encode", "publish",
        "manufacture", "deploy", "execute", "implement", "synthesize", "translate",
    ),
    Regime.CORRECTION: (
        "review", "appeal", "audit", "overturn", "reverse", "vacate", "inspect",
        "moderate", "remediate", "rollback", "adjudicate", "correct", "repair",
        "quality control", "quality-control", "verify upstream", "oversight",
    ),
    Regime.SELECTION: (
        "vote", "elect", "pass legislation", "select", "prioritize", "allocate",
        "award", "rank candidates", "admissions", "funding decision", "procure",
    ),
}


@dataclass
class RegimeCall:
    regime: Regime
    confidence: float          # 0–1, keyword-margin heuristic; override with `declared`
    rationale: str

    def to_dict(self) -> dict:
        d = asdict(self); d["regime"] = self.regime.value; return d


def classify_channel(role_description: str = "",
                     declared: Optional[Regime] = None) -> RegimeCall:
    """Gate 0. Classify a channel's ROLE before any law is applied.

    `declared` (an explicit institutional declaration of the channel's function)
    always wins over the keyword heuristic — the heuristic exists to catch the
    case where nobody asked the question at all, which is exactly how the
    judicial campaign went wrong."""
    if declared is not None:
        return RegimeCall(declared, 1.0, "explicitly declared by the architect")
    text = (role_description or "").lower()
    scores = {r: sum(1 for kw in kws if kw in text) for r, kws in _RUBRIC.items()}
    best = max(scores, key=scores.get)
    top, rest = scores[best], sorted(scores.values())[-2] if len(scores) > 1 else 0
    if top == 0:
        return RegimeCall(Regime.UNKNOWN, 0.0,
                          "no regime keywords found — declare the channel's role "
                          "explicitly; refusing to guess is the point of Gate 0")
    conf = min(1.0, 0.4 + 0.2 * (top - rest))
    hits = [kw for kw in _RUBRIC[best] if kw in text][:4]
    return RegimeCall(best, round(conf, 2), f"keyword evidence: {hits}")


# ─────────────────────────────────────────────────────────────────────────────
# 4. Regime-aware E prediction (refuses category errors instead of committing them)
# ─────────────────────────────────────────────────────────────────────────────

class RegimeError(ValueError):
    """Raised when a law is requested for a channel it does not govern."""


@dataclass
class PredictedE:
    value: float
    law: str
    status: str
    regime: str
    note: str

    def to_dict(self) -> dict:
        return asdict(self)


def predict_E(U: float,
              regime: Regime,
              D: Optional[float] = None,
              D_in: Optional[float] = None,
              q: Optional[float] = None,
              kappa: float = 1.0) -> PredictedE:
    """Predict realized output under the regime's own law.

    TRANSMISSION: requires D (the channel's own two-hop fidelity).
    CORRECTION : requires D_in (fidelity of the INCOMING signal) and q (the
                 corrector's own decode quality). Result is HYPOTHESIS-tagged.
    SELECTION / UNKNOWN: refused, with the reason."""
    if regime == Regime.TRANSMISSION:
        if D is None:
            raise RegimeError("transmission law needs D (own two-hop fidelity)")
        return PredictedE(float(U * D), "E = U*D", LawStatus.SUPPORTED.value,
                          regime.value, "engine law; linear, multi-domain supported")
    if regime == Regime.CORRECTION:
        if D_in is None or q is None:
            raise RegimeError("correction law needs D_in (incoming fidelity) and q "
                              "(corrector's own decode quality)")
        return PredictedE(float(U * kappa * (1.0 - D_in) * q),
                          "E_c = U*kappa*(1-D_in)*q", LawStatus.HYPOTHESIS.value,
                          regime.value,
                          "PUMP LAW — HYPOTHESIS. Post-hoc from BGer; do not report "
                          "as validated until P1–P2 (see preregistered_predictions) "
                          "pass out-of-sample.")
    if regime == Regime.SELECTION:
        raise RegimeError("no validated D-law for SELECTION channels (legislative "
                          "null: power covariates dominate). Model with the "
                          "channel's own covariates; do not launder an exponent.")
    raise RegimeError("regime UNKNOWN — run classify_channel / Gate 0 first; "
                      "refusing to apply a law to an unclassified channel is "
                      "the lesson of the judicial campaign.")


# ─────────────────────────────────────────────────────────────────────────────
# 5. Exponent-signature diagnostics (turns the BGer episode into an instrument)
# ─────────────────────────────────────────────────────────────────────────────

def diagnose_exponent(k_hat: float,
                      ci: Sequence[float],
                      inversion_observed: Optional[bool] = None,
                      dead_D: bool = False) -> dict:
    """Read a fitted E = U·D^k the way v18.1 says it must be read.

    Maps the fitted signature to a regime diagnosis instead of a naive
    law-verdict. `inversion_observed`: True if low-fidelity categories carry
    HIGHER observable output (the fidelity–influence inversion).
    `dead_D`: True if the D channel had ~zero variance (placeholder)."""
    lo, hi = float(ci[0]), float(ci[1])
    if dead_D:
        return {"diagnosis": "DEAD_CHANNEL",
                "action": "Do not report any verdict. D was uninstantiable "
                          "(legislative mode: D_gap = D_enc identically). "
                          "Fix instrumentation; the scout's Gates 1–3 exist for this."}
    if lo <= 1.0 <= hi and not (lo <= 2.0 <= hi):
        return {"diagnosis": "TRANSMISSION_CONSISTENT",
                "action": "Linear engine law consistent. Log to ledger via "
                          "pre-registered protocol only."}
    if lo <= 2.0 <= hi and not (lo <= 1.0 <= hi):
        return {"diagnosis": "SUPERLINEAR_ANOMALY",
                "action": "Quadratic-consistent fit. FLAG, do not adopt: no other "
                          "domain supports it; check E/D construct validity first."}
    if hi < 0.5:
        if inversion_observed:
            return {"diagnosis": "CORRECTION_REGIME_SIGNATURE",
                    "action": "k≈0/negative + fidelity–influence inversion = the pump "
                              "signature. Do NOT report as GT falsification. Reclassify "
                              "channel as R_C, re-derive E as repair-durability (not "
                              "influence), and route to the H_C pre-registration."}
        return {"diagnosis": "NO_COUPLING_IN_THIS_SPEC",
                "action": "k≈0 without a detected inversion: either the E–D pair is "
                          "causally unlinked here or the construct is wrong. Report "
                          "'form not supported in this spec'; test the R_C signature "
                          "explicitly before concluding anything stronger."}
    return {"diagnosis": "INDETERMINATE",
            "action": "CI too wide or intermediate. More data or better D resolution."}


def correction_signature_check(median_E_by_class: dict) -> dict:
    """P2 helper — encodes the BGer five-level ordering as a reusable test.

    Expects keys among: writeoff, inadmissible, rejected, granted, partly_granted.
    PASS iff non-engagement < inspection-only < repair-delivered."""
    g = median_E_by_class.get
    need = ("rejected",)
    if any(k not in median_E_by_class for k in need):
        return {"pass": None, "why": "need at least 'rejected' plus one other class"}
    non_engage = [v for k, v in median_E_by_class.items()
                  if k in ("writeoff", "inadmissible")]
    repaired = [v for k, v in median_E_by_class.items()
                if k in ("granted", "partly_granted")]
    ok = True; notes = []
    if non_engage:
        ok &= max(non_engage) < g("rejected"); notes.append("non-engagement < inspection")
    if repaired:
        ok &= min(repaired) > g("rejected"); notes.append("repair > inspection")
    return {"pass": bool(ok), "why": "; ".join(notes),
            "open_detail_P4": "full vs partial ordering unresolved (BGer: partly ≈ granted)"}


# ─────────────────────────────────────────────────────────────────────────────
# 6. Locked, directional predictions (the price of naming a post-hoc law)
# ─────────────────────────────────────────────────────────────────────────────

def preregistered_predictions() -> list[dict]:
    return [
        {"id": "P1", "dataset": "SCDB (Spaeth), out-of-sample",
         "prediction": "precedentAlteration=1 or declarationUncon=1 → HIGHER later "
                       "citation in-degree than matched cases (length/issue controlled)",
         "direction_locked": True, "status": "UNTESTED"},
        {"id": "P2", "dataset": "BGer temporal hold-out (unseen years)",
         "prediction": "five-level ordering reproduces; granted vs rejected premium "
                       "in 1.15–1.35× band, length-adjusted",
         "direction_locked": True, "status": "UNTESTED"},
        {"id": "P3", "dataset": "GitHub cohort (negative control, TRANSMISSION)",
         "prediction": "NO inversion: corr(E, D) > 0",
         "direction_locked": True, "status": "CONSISTENT (existing data), re-run locked"},
        {"id": "P4", "dataset": "BGer / SCDB",
         "prediction": "full vs partial reversal ordering — OPEN. Naive pump law says "
                       "full > partial; BGer medians say partly(5) ≥ granted(4). "
                       "Test, do not assume.",
         "direction_locked": False, "status": "UNTESTED"},
    ]


def spec_sha() -> str:
    """SHA-256 of this module + the ledger + predictions — commit before P1/P2 run."""
    h = hashlib.sha256()
    with open(__file__, "rb") as f:
        h.update(f.read())
    h.update(json.dumps(EMPIRICAL_LEDGER, sort_keys=True).encode())
    h.update(json.dumps(preregistered_predictions(), sort_keys=True).encode())
    return h.hexdigest()


# ─────────────────────────────────────────────────────────────────────────────
# 7. Self-test — TRANSPARENTLY SYNTHETIC (proves the diagnostics, not the law)
# ─────────────────────────────────────────────────────────────────────────────

def _selftest():
    import numpy as np
    import statsmodels.api as sm
    rng = np.random.default_rng(7)
    n = 20000
    print("═" * 74)
    print("  gt_regimes v18.1 SELF-TEST — synthetic worlds, real diagnostics")
    print("═" * 74)
    print(f"  COMMIT SHA-256: {spec_sha()[:32]}…\n")

    # World A: a true TRANSMISSION channel, E = U·D · noise
    U = rng.lognormal(0, 0.5, n)
    D = np.clip(rng.beta(5, 2, n), 0.02, 1)
    E = U * D * rng.lognormal(0, 0.3, n)
    X = sm.add_constant(np.column_stack([np.log(U), np.log(D)]))
    k = sm.OLS(np.log(E), X).fit()
    ci = k.conf_int()[2]
    dA = diagnose_exponent(k.params[2], ci, inversion_observed=False)
    print(f"  [A] synthetic engine   : k̂={k.params[2]:+.2f} CI[{ci[0]:.2f},{ci[1]:.2f}] "
          f"→ {dA['diagnosis']}")

    # World B: a true CORRECTION channel measured with the WRONG (transmission) law
    D_in = np.clip(rng.beta(5, 2, n), 0.02, 0.98)
    q = np.clip(rng.beta(6, 2, n), 0.05, 1)
    E_c = U * (1 - D_in) * q * rng.lognormal(0, 0.3, n) + 1e-6
    Xb = sm.add_constant(np.column_stack([np.log(U), np.log(D_in)]))
    kb = sm.OLS(np.log(E_c), Xb).fit()
    cib = kb.conf_int()[2]
    dB = diagnose_exponent(kb.params[2], cib, inversion_observed=True)
    print(f"  [B] pump, wrong law    : k̂={kb.params[2]:+.2f} CI[{cib[0]:.2f},{cib[1]:.2f}] "
          f"→ {dB['diagnosis']}")

    # World B measured with the RIGHT law recovers structure
    Xc = sm.add_constant(np.column_stack([np.log(U), np.log(1 - D_in), np.log(q)]))
    kc = sm.OLS(np.log(E_c), Xc).fit()
    print(f"      pump, pump law     : exponents on [U, (1−D_in), q] = "
          f"[{kc.params[1]:.2f}, {kc.params[2]:.2f}, {kc.params[3]:.2f}]  (≈1,1,1 ✓)")

    # Gate 0 + refusal behavior
    court = classify_channel("appellate body that reviews and may reverse or vacate "
                             "lower-court rulings; oversight and audit function")
    pipe = classify_channel("CI pipeline that builds, tests and ships releases")
    print(f"\n  Gate 0: court → {court.regime.value} ({court.confidence});  "
          f"pipeline → {pipe.regime.value} ({pipe.confidence})")
    try:
        predict_E(U=1.0, regime=Regime.UNKNOWN, D=0.9)
    except RegimeError as e:
        print(f"  Refusal check (UNKNOWN): RegimeError ✓ — {str(e)[:60]}…")
    ec = predict_E(U=1.0, regime=Regime.CORRECTION, D_in=0.3, q=0.9)
    print(f"  Pump prediction tagged : status={ec.status} ✓")

    sig = correction_signature_check(
        {"writeoff": 1, "inadmissible": 1, "rejected": 3, "granted": 4, "partly_granted": 5})
    print(f"  BGer-ordering encoder  : pass={sig['pass']} ({sig['why']})")

    print("\n  NOTE: worlds A/B are SYNTHETIC. This test validates the diagnostics")
    print("  and refusal logic, not the correction law. H_C stays HYPOTHESIS until")
    print("  P1–P2 run out-of-sample under the committed SHA above.")
    print("═" * 74)


if __name__ == "__main__":
    _selftest()
